alias aseprite="sh ~/Documents/shell/Aseprite.sh"
alias spicetify="~/spicetify-cli/spicetify"
alias pingSteamSEA1="ping sgp-1.valve.net"
alias pingSteamSEA2="ping sgp-2.valve.net"
alias pingSteamIndia="ping 116.202.224.146"
